name: Publish Package

on:
  push:
    branches:
      - '*' # matches every branch that doesn't contain a '/'
      - '*/*' # matches every branch containing a single '/'
      - '**' # matches every branch
      - '!main' # excludes main
      - '!master' # excludes master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          npm config set //npm.pkg.github.com/:_authToken=\${NPM_TOKEN}
          yarn install --frozen-lockfile --ignore-engines
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: yarn clean && yarn build
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish as NPM packages
        run: |
          git stash
          npm config set //registry.npmjs.org/:_authToken=\${NPM_TOKEN}
          yarn release:canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
